config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :recipes, only: [:show,:new,:create, :edit, :update]
  resources :cuisines, only: [:show,:new,:create, :edit, :update]
  resources :recipe_types, only: [:show,:new,:create, :edit, :update]
  post :search, to: 'home#search'
  get :all_recipes, to: 'home#all_recipes'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
 has_many :recipes
 validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :recipe_type
  validates :title, presence: true
  validates :recipe_type_id, presence: true
  validates :cuisine_id, presence: true
  validates :cook_time, presence: true
  validates :ingredients, presence: true
  validates :method, presence: true
  validates :difficulty, presence: true
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :set_cuisine, only:[:show,:edit,:update]

  def show
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(cuisine_params)
    if @cuisine.save
      redirect_to cuisine_url(@cuisine.id)
    else
      flash[:error] = "Você deve informar o nome da cozinha"
      render :new
    end
  end

  def edit
  end

  def update
    @cuisine.update(cuisine_params)
    if @cuisine.valid?
      redirect_to cuisine_url(@cuisine.id)
    else
      flash[:error] = "Você deve informar o nome da cozinha"
      render :edit
    end
  end

  private

  def cuisine_params
      params.require(:cuisine).permit(:name)
  end
  def set_cuisine
    @cuisine = Cuisine.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.last(6)
    @cuisines = Cuisine.all()
    @recipe_types = RecipeType.all()
  end

  def search
    @search = params[:search]
    @recipes = Recipe.where("title LIKE ?", "%#{@search}%")
    render :results_search
  end

  def all_recipes
    @recipes = Recipe.all()
    render :all_recipes
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  before_action :set_recipe_type, only:[:show,:edit,:update]

  def show
  end

  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(recipe_type_params)
    if @recipe_type.save
      redirect_to recipe_type_url(@recipe_type.id)
    else
      flash[:error] = "Você deve informar o nome do tipo de receita"
      render :new
    end
  end

  def edit
  end

  def update
    @recipe_type.update(recipe_type_params)
    if @recipe_type.valid?
      redirect_to recipe_type_url(@recipe_type.id)
    else
      flash[:error] = "Você deve informar o nome do tipo de receita"
      render :edit
    end
  end

  private

  def recipe_type_params
      params.require(:recipe_type).permit(:name)
  end
  def set_recipe_type
    @recipe_type = RecipeType.find(params[:id])
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_collections, only:[:new,:edit]
  before_action :set_recipe, only:[:show,:edit,:update]

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipe_url(@recipe.id)
    else
      flash[:error] = "Você deve informar todos os dados da receita"
      set_collections
      render :new
    end
  end

  def edit
  end

  def update
    @recipe.update(recipe_params)
    if @recipe.valid?
      redirect_to recipe_url(@recipe.id)
    else
      flash[:error] = "Você deve informar todos os dados da receita"
      set_collections
      render :edit
    end
  end

  private

  def recipe_params
      params.require(:recipe).permit(:title, :recipe_type_id,
                                     :cook_time, :cuisine_id, :ingredients,
                                     :method, :difficulty)
  end

  def set_collections
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cuisines/_form.html.erb
<%= form_for(@cuisine) do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/cuisines/edit.html.erb
<h1>Editar Cozinha</h1>
<main>
  <%= render 'form' %>
</main>

app/views/cuisines/new.html.erb
<h1>Editar Cozinha</h1>
<main>
  <%= form_for(@cuisine) do |f| %>
    <div>
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit 'Enviar' %>
  <% end %>
</main>

app/views/cuisines/show.html.erb
<h1><%=@cuisine.name%></h1>
<main>
<% if @cuisine.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo de cozinha</p>

<% else %>
  <% @cuisine.recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
<% end %>
</main>
<%= link_to 'Editar', edit_cuisine_path%>
<%= link_to 'Voltar', root_path%>

app/views/home/_form_search.html.erb
<%= form_tag search_path do  %>

    <%= label_tag :search, 'Busca' %>
    <%= text_field_tag :search %>
    <%= submit_tag 'Buscar' %>

<% end %>

app/views/home/all_recipes.html.erb
<main>
  <h2>Todas as receitas</h2>
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
  <%= link_to 'Voltar',root_path %>
</main>

app/views/home/index.html.erb
<div class="row">
  <aside>
    <div class="col-md-3 col-sm-12">
      <h2>Tipos de Cozinhas</h2>
      <% @cuisines.each do |cuisine| %>
        <li><%= link_to cuisine.name, cuisine%></li>
      <% end %>

      <h2>Tipos de Receitas</h2>
      <% @recipe_types.each do |recipe_type| %>
        <li><%= link_to recipe_type.name, recipe_type%></li>
      <% end %>
    </div>
  </aside>


  <main>
    <div class="col-md-9 col-sm-12">
      <h2>Útimas receitas</h2>
      <% @recipes.each do |recipe| %>
        <%= render recipe %>
      <% end %>
      <%= link_to 'Ver todas receitas', all_recipes_path %>
    </div>
  </main>
</div>

app/views/home/results_search.html.erb
<h1> Resultado da busca por: <%= @search %> </h1>

<% @recipes.each do |recipe| %>
  <%= render recipe %>
<% end %>

<% if @recipes.empty? %>
  Nenhum resultado encontrado.
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Cookbook</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="text-center topo">
      <div class="container">
        <h1>CookBook</h1>
        <p>Bem-vindo ao maior livro de receitas online</p>
          <%= link_to 'Enviar uma receita', new_recipe_path %>
          <%= link_to 'Enviar uma cozinha', new_cuisine_path %>
          <%= link_to 'Enviar um tipo receita', new_recipe_type_path %>
          <%= render "home/form_search" %>
      </div>
    </header>
    <div class="container">
      <% if flash[:error]%>
        <%= flash[:error]%>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipe_types/_form.html.erb
<%= form_for(@recipe_type) do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/recipe_types/edit.html.erb
<h1>Editar Tipo de Receita</h1>
<main>
  <%= render 'form' %>
</main>

app/views/recipe_types/new.html.erb
<h1>Inserir Tipo de Receita</h1>
<main>
  <%= form_for(@recipe_type) do |f| %>
    <div>
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit 'Enviar' %>
  <% end %>
</main>

app/views/recipe_types/show.html.erb
<h1><%=@recipe_type.name%></h1>
<main>
<% if @recipe_type.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo de receitas</p>
<% else %>
  <% @recipe_type.recipes.each do |recipe_type| %>
    <%= render recipe_type %>
  <% end %>
<% end %>
</main>
<%= link_to 'Editar', edit_recipe_type_path%>
<%= link_to 'Voltar', root_path%>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <div>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :recipe_type_id, 'Tipo da Receita' %>
    <%= f.collection_select(:recipe_type_id, @recipe_types, :id, :name) %>
  </div>
  <div>
    <%= f.label :cuisine_id, 'Cozinha' %>
    <%= f.collection_select(:cuisine_id, @cuisines, :id, :name) %>
  </div>
  <div>
    <%= f.label :difficulty, 'Dificuldade' %>
    <%= f.text_field :difficulty %>
  </div>
  <div>
    <%= f.label :cook_time, 'Tempo de Preparo' %>
    <%= f.text_field :cook_time %>
  </div>
  <div>
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_area :ingredients %>
  </div>
  <div>
    <%= f.label :method, 'Como Preparar' %>
    <%= f.text_area :method %>
  </div>

  <%= f.submit 'Enviar' %>
<% end %>

app/views/recipes/_recipe.html.erb
<h1><%= link_to recipe.title, recipe %></h1>
<ul>
  <li><%= recipe.recipe_type.name%></li>
  <li><%= recipe.cuisine.name%></li>
  <li><%= recipe.difficulty%></li>
  <li><%= recipe.cook_time%> minutos</li>
</ul>

app/views/recipes/edit.html.erb
<h1>Editar Receita</h1>
<main>
  <%= render 'form' %>
</main>

app/views/recipes/new.html.erb
<h1>Inserir Receita</h1>
<main>
  <%= render 'form' %>
</main>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<main>
  <h3>Detalhes</h3>
  Tipo de cozinha:<p><%=@recipe.recipe_type.name%></p>
  Cozinha: <p><%=@recipe.cuisine.name%></p>
  Dificuldade:<p><%=@recipe.difficulty%></p>
  Tempo de preparo: <p><%=@recipe.cook_time%> minutos</p>

  <h3>Ingredientes</h3>
  <p><%=@recipe.ingredients%></p>

  <h3>Como Preparar</h3>
  <p><%=@recipe.method%></p>
</main>
  <%= link_to 'Editar', edit_recipe_path%>
  <%= link_to 'Voltar', root_path%>